In [2]:
import pandas as pd
import numpy as np

In [3]:
Moeller = pd.read_excel('Moeller.xlsx')

In [4]:
Moeller['PER'] = round((Moeller['PTS'] + Moeller['AST'] + Moeller['STL'] + Moeller['BLK'] - (Moeller['FGA'] - Moeller['FGM']) - (Moeller['FTA']-Moeller['FTM']) - Moeller['TO'])/(Moeller['GMS']),2)

In [5]:
Moeller[['Player', 'PER']].sort_values(by='PER', ascending=False)

             Player    PER
0     Evan Mahaffey  15.00
1     Donovan Mukes   6.43
2    Connor Marklay   5.95
3       Yoro Diallo   5.05
5        AJ McBride   2.55
4     Nick Williams   2.38
7       Kyle Havens   2.31
8        Matt Meyer   1.10
6   Grant Smethwick   1.05
10    Kingston Land   1.00
11     Rayn Hassane   0.54
13    Elijah Turner   0.47
14    Jason Henning   0.33
12    Dwight Turner   0.17
9       Talan Noyes  -1.17

In [6]:
Lasalle = pd.read_excel('Lasalle.xlsx')
Lasalle

,Player,GMS,FGM,FGA,FTM,FTA,3PM,3PA,PTS,OFF,DEF,TOT,AST,TO,STL,BLK,PF
0,Nick Heffron,19,61,138,44,67,38,97,204,8,40,48,19,28,10,8,48
1,JJ Ruffin,18,68,129,25,48,0,2,161,24,81,105,54,36,14,20,41
2,Roman Severt,19,52,116,12,15,33,83,149,12,22,34,12,18,6,1,27
3,Drae Arnold,16,32,89,26,45,3,20,93,10,44,54,18,54,20,6,31
4,Cam Cope,19,35,91,30,41,9,28,109,13,43,56,42,49,31,2,40
5,Brady Schneider,16,32,64,17,33,4,10,85,22,18,40,14,21,10,3,44
6,Ian Bierbaum,18,23,67,2,3,22,61,70,1,16,17,6,11,10,1,13
7,Dylan Eddings,10,12,31,7,13,0,4,31,6,13,19,7,10,3,1,10
8,Brandon Richardson,13,10,18,3,5,0,0,23,3,3,6,1,3,3,2,7
9,Tony LaMarca,7,5,10,2,6,0,2,12,1,3,4,1,1,3,0,2
10,Patrick McLaughlin,10,3,10,5,6,2,7,13,1,4,5,6,1,2,0,4
11,Brady O'Connor,14,4,11,1,2,0,2,9,7,19,26,2,6,3,2,6
12,Jake Rhodes,4,0,1,2,5,0,0,2,1,2,3,0,1,1,0,2
13,Anthony Holmes,8,0,5,2,2,0,1,2,1,7,8,2,5,1,1,3
14,Max English,7,0,1,0,0,0,0,0,0,0,0,0,0,0,0,2

In [39]:
Lasalle['PER'] = round((Lasalle['PTS'] + Lasalle['AST'] + Lasalle['STL'] + Lasalle['BLK'] - (Lasalle['FGA'] - Lasalle['FGM']) - (Lasalle['FTA']-Lasalle['FTM']) - Lasalle['TO'])/(Lasalle['GMS']),2)

In [40]:
Lasalle[['Player', 'PER']].sort_values(by='PER', ascending=False)

                Player   PER
1            JJ Ruffin  7.17
0         Nick Heffron  5.95
2         Roman Severt  4.37
4             Cam Cope  3.58
5      Brady Schneider  2.69
6         Ian Bierbaum  1.72
8   Brandon Richardson  1.23
10  Patrick McLaughlin  1.20
9         Tony LaMarca  0.86
7        Dylan Eddings  0.70
3          Drae Arnold  0.44
11      Brady O'Connor  0.14
14         Max English -0.14
12         Jake Rhodes -0.50
13      Anthony Holmes -0.50